project_id = "quvuhzmguvgfcirpauog"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://quvuhzmguvgfcirpauog.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_users = false

[edge_functions]
enabled = true

[functions.top]
verify_jwt = false

[functions.admin-refresh]
verify_jwt = false

[functions.social-blade-top]
verify_jwt = false

[functions.admin-refresh-all]
verify_jwt = false

[functions.avatar-enrichment]
verify_jwt = false

[functions.subscribe]
verify_jwt = false

[functions.weekly-diff-email]
verify_jwt = false

[functions.weekly-refresh]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.sync-beehiiv]
verify_jwt = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324